"""Added grade model

Revision ID: bd9ce00880f9
Revises: 4b9cc85f5ad5
Create Date: 2024-10-17 10:53:26.935847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9ce00880f9'
down_revision = '4b9cc85f5ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_subject')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('pin_no')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('pin_no')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('pin_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pin_no_hash')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pin_no_hash')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_no', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pin_no_hash')

    op.create_table('student_subject',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    op.drop_table('grades')
    # ### end Alembic commands ###
