"""Add admission_number to Student

Revision ID: d616143af555
Revises: 4b9cc85f5ad5
Create Date: 2024-10-21 17:33:26.492069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd616143af555'
down_revision = '4b9cc85f5ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('admin_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('pin_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_grade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('guardian_contact', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('guardian_email', sa.String(length=50), nullable=False))
        batch_op.alter_column('admission_no',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('pin_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('pin_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('pin_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pin_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('admission_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('guardian_email')
        batch_op.drop_column('guardian_contact')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('address')
        batch_op.drop_column('general_grade')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('pin_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('admin_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
